# Generated by Django 5.2.8 on 2025-11-06 01:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('identificacion', models.CharField(max_length=20, unique=True, verbose_name='Documento/NIT')),
                ('direccion', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=20)),
                ('tipo_documento', models.CharField(default='NIT', max_length=10, verbose_name='Tipo Documento')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo')),
                ('tipo_pago', models.CharField(choices=[('CONTADO', 'Contado'), ('CREDITO', 'Crédito'), ('MIXTO', 'Mixto')], default='CONTADO', max_length=10)),
                ('credito_maximo', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Crédito Máximo')),
                ('estado', models.CharField(default='activo', max_length=10)),
                ('municipio', models.CharField(max_length=100, verbose_name='Municipio de Residencia')),
            ],
            options={
                'db_table': 'cliente',
            },
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre del Departamento')),
                ('codigo', models.CharField(max_length=10, unique=True, verbose_name='Código Dpto')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
                'db_table': 'departamento',
            },
        ),
        migrations.CreateModel(
            name='LineaProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre de Línea')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Línea de Producto',
                'verbose_name_plural': 'Líneas de Producto',
                'db_table': 'linea_producto',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=150)),
                ('rol', models.CharField(max_length=50, verbose_name='Rol en el Sistema')),
            ],
            options={
                'verbose_name': 'Usuario del Sistema',
                'verbose_name_plural': 'Usuarios del Sistema',
                'db_table': 'usuario',
            },
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Municipio')),
                ('codigo', models.CharField(max_length=10, unique=True, verbose_name='Código Mpio')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='back.departamento', verbose_name='Departamento')),
            ],
            options={
                'verbose_name': 'Municipio',
                'verbose_name_plural': 'Municipios',
                'db_table': 'municipio',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del Producto')),
                ('codigo', models.CharField(max_length=50, unique=True, verbose_name='Código de Producto')),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Unitario')),
                ('stock', models.IntegerField(default=0, verbose_name='Stock')),
                ('aplica_iva', models.BooleanField(default=True, verbose_name='Aplica IVA')),
                ('linea_producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='back.lineaproducto', verbose_name='Línea de Producto')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'db_table': 'producto',
            },
        ),
        migrations.CreateModel(
            name='ProductoImagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_imagen', models.URLField(max_length=500, verbose_name='URL de la Imagen')),
                ('es_principal', models.BooleanField(default=False, verbose_name='Imagen Principal')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='back.producto', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Imagen de Producto',
                'verbose_name_plural': 'Imágenes de Producto',
                'db_table': 'producto_imagen',
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_factura', models.CharField(max_length=50, unique=True, verbose_name='Número de Factura')),
                ('fecha_venta', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora')),
                ('forma_pago', models.CharField(choices=[('CONTADO', 'Contado'), ('CREDITO', 'Crédito')], default='CONTADO', max_length=10, verbose_name='Forma de Pago')),
                ('total_general', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Total General')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='back.cliente', verbose_name='Cliente')),
                ('usuario_vendedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='back.usuario', verbose_name='Vendedor')),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
                'db_table': 'venta',
            },
        ),
        migrations.CreateModel(
            name='VentaDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(verbose_name='Cantidad')),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Unitario de Venta')),
                ('porcentaje_iva', models.DecimalField(decimal_places=2, default=0.19, max_digits=5, verbose_name='Porcentaje IVA')),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Total Detalle')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='back.producto', verbose_name='Producto')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='back.venta', verbose_name='Venta')),
            ],
            options={
                'verbose_name': 'Detalle de Venta',
                'verbose_name_plural': 'Detalles de Venta',
                'db_table': 'venta_detalle',
                'unique_together': {('venta', 'producto')},
            },
        ),
    ]
