# Generated by Django 5.2.8 on 2025-11-11 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BACKVENTAS', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='opciones',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='sku',
        ),
    ]
