# Generated by Django 5.2.8 on 2025-11-13 01:40

import djongo.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BACKVENTAS', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productoimagen',
            name='id',
        ),
        migrations.AddField(
            model_name='productoimagen',
            name='_id',
            field=djongo.models.fields.ObjectIdField(auto_created=True, default='!', primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
