# Generated by Django 5.2.8 on 2025-11-13 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BACKVENTAS', '0002_remove_productoimagen_id_productoimagen__id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productoimagen',
            options={'managed': False},
        ),
    ]
