# Generated by Django 5.2.8 on 2025-11-11 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BACKVENTAS', '0002_remove_producto_opciones_remove_producto_sku'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productoimagen',
            name='metadata',
        ),
    ]
