# Generated by Django 5.2.8 on 2025-11-13 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BACKVENTAS', '0003_alter_productoimagen_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='productoimagen',
            table='BACKVENTAS_productoimagen',
        ),
    ]
