# Generated by Django 5.2.8 on 2025-11-11 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BACKVENTAS', '0003_remove_productoimagen_metadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productoimagen',
            name='producto',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
