# Generated by Django 5.2.8 on 2025-11-11 03:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BACKVENTAS', '0004_alter_productoimagen_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productoimagen',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='BACKVENTAS.producto'),
        ),
    ]
