# Generated by Django 5.2.8 on 2025-11-11 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BACKVENTAS', '0005_alter_productoimagen_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='productoimagen',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
