# Generated by Django 5.2.8 on 2025-11-11 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BACKVENTAS', '0006_productoimagen_metadata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productoimagen',
            name='metadata',
        ),
    ]
