# Generated by Django 5.2.8 on 2025-11-11 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BACKVENTAS', '0007_remove_productoimagen_metadata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productoimagen',
            name='url_almacenamiento',
        ),
        migrations.AddField(
            model_name='productoimagen',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='productos/imagenes/'),
        ),
    ]
