# Generated by Django 5.2.8 on 2025-11-11 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BACKVENTAS', '0008_remove_productoimagen_url_almacenamiento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='password_hash',
        ),
    ]
